vicr123/AstralMod

bot.js
This edit adds me to the time command
This will not affect the bot in anyway if you decide to merge this request
=> Added my name to the time command as hours = 0

bot.js
Add's kys logs to ALA
Please test this if merged on ALA discord
=> Add ALA to KYS logs

bot.js
This pull request has not been tested and might not work, but it **should** work
=> Improve getBoshyTime

bot.js
That was fun (not)
This PR hasn't been tested / checked for errors yet.
=> Change uptime from ms to hours

bot.js
=> Possible fix for uptime

bot.js
=> Revert "Possible fix for uptime"

bot.js
=> Revert "Revert "Possible fix for uptime""

bot.js
I've made use of the new "[member].tag" feature included in Discord.js v11.1, replacing "u.username + "#" + u.discriminator". I've also included more error handling, both for unhandled promises and if the mod:rm "num" variable is greater than 99 (as you can't delete more than 99 messages in Discord at a time through the API).
=> General minor improvements and better error handling

bot.js
Just added @here to the @everyone detection. I tested it just in case it didn't work ;)
EDIT: Also added that 'verified' phrase to the nickname expletive check.
=> Added @here to everyone detection

bot.js
Untested, could contain errors.
Please check the PR closely before merging :)
=> Make mute action toggle timeout

bot.js
Untested, but *should* work.
Also implements a stopchat command which removes the Weekly Chat role from everyone that has it.
=> Possibly implemented Weekly Chat role

bot.js
Also fixes the "Clear" bug for nicknames (yay!)
=> Fix the "Cancel" bug

bot.js
=> Changed "his" to "their"

plugins/retrsettings.js, plugins/spam.js, plugins/time.js, plugins/userman.js, plugins/warning.js
I've gone through all the files in AstralMod, and I've made changes to help improve consistency and grammar.
=> Minor grammatical changes and fixes

bot.js
Added code blocks around names to prevent pinging people, and removed full stop from username changes.
=> Update "userUpdate" and "guildMemberUpdate"

bot.js
Added an extra sentence in the second step of the config for those having a little trouble getting a channel ID. (No extra lines were made, so hopefully AM doesn't crash)
=> Some extra help

bot.js, plugins/flag.js, plugins/monitor.js, plugins/spam.js, plugins/time.js, plugins/userman.js, plugins/warning.js
Just some minor updates to certain pieces of code, specifically the refactoring of `startTyping` and `stopTyping` code, which should hopefully fix the endless typing bug. This change requires discord.js v11.3.
=> Minor refactors and QOL changes to code/grammar

plugins/flag.js
I have completely refactored the pinning system, fixed some bugs and typos and introduced some new features, such as
This PR has been tested thoroughly, however there are some known bugs, such as the text truncation not cutting emojis or Arabic text correctly.
Performance should also be improved slightly due to less clutter.
=> Refactor to flag/pin system

plugins/eval.js
Uses AsyncFunction instead of smelly eval().
=> Make am:exec work with async

bot.js, plugins/weather.js
Air pressure is represented correctly, fixed "Cannot read property 'condition' of undefined", and the time at which the weather data was published is now displayed
=> Quality-of-life improvements to am:weather
